### ISSUE TITLE
Remembering that user has completed two-factor authentication until logout

### ISSUE THREAD

**Issue by alertiu5** [scheb/two-factor-bundle#116]
Good day.

I've been trying to use the bundle to enable two-factor authentication via Google Authenticator for backoffice app of our site as a whole. However, with configuration I currently have, once I pass authentication at /2fa_check, I get redirected to /, then it sends me to /login and then to /2fa which asks me to provide a 2fa code again, which makes it impossible to actually work with application. I tried to change two_factor.default_target_path to another path which can be accessed anonymously and if I check for token there it says I have a TwoFactorToken which has $token->allTwoFactorProvidersAuthenticated() equal to false, while wrapped UsernamePasswordToken is authenticated and has all the roles, including our default ROLE_CRM_USER.

The only workaround I have found is to forcefully send _trusted=1 via hidden field in custom 2fa.html.twig template and enabling trusted_device cookie option. However, there's a tangible difference between marking a device as trusted via a cookie and just allowing a user to work freely until he logs out.

I suspect I have just made some mistake in my security configuration, but if it is indeed working as intended I would suggest adding an option to check a certain value in session for the fact that user has indeed passed the additional check, similar to how you describe it in your article at https://www.christianscheb.de/archives/14. (Setting that value in two-factor success handler and checking for its existence in TwoFactorListener::handle(), perhaps?)

Excerpt from my current config is below:
```
security:
    encoders:
        CrmBundle\Entity\User\User:
            algorithm: sha1
            encode_as_base64: false
            iterations: 1

    role_hierarchy:
        ROLE_CRM_USER: ROLE_USER

    providers:
        user_provider:
            id: platform.user.provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: user_provider
            host: 'crm.%domain%'
            pattern:    ^/
            form_login:
                use_referer: true
                default_target_path: /
                login_path:  /login
                check_path:  /login
            logout:
                path:   /logout
                target: /
                invalidate_session: true
            remember_me:
                secret:   '%secret%'
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER
            two_factor:
                auth_form_path: /2fa                   # Path or route name of the two-factor form
                check_path: /2fa_check                 # Path or route name of the two-factor code check
                default_target_path: /                 # Where to redirect by default after successful authentication
                always_use_default_target_path: true   # If it should always redirect to default_target_path
                multi_factor: false                    # If ALL active two-factor methods need to be fulfilled (multi-factor authentication)

    access_control:
        - { path: ^/api/login, roles: [ IS_AUTHENTICATED_FULLY ] }
        - { path: ^/api, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }
        - { path: ^/demo/secured/hello/admin/, roles: [ ROLE_ADMIN ] }
        - { host: 'crm.%domain%', path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { host: 'crm.%domain%', path: ^/2fa, role: IS_AUTHENTICATED_2FA_IN_PROGRESS }
        - { host: 'crm.%domain%', path: ^/dictionary, roles: [IS_AUTHENTICATED_ANONYMOUSLY, ROLE_CRM_USER ]}
        - { host: 'crm.%domain%', path: ^/, roles: ROLE_CRM_USER }

```
bundle configuration, just in case:
```
scheb_two_factor:

    # Trusted computer feature
    trusted_device:
        enabled: true                  # If the trusted computer feature should be enabled
        cookie_name: trusted_device    # Name of the trusted computer cookie
        cookie_secure: false           # Set the 'Secure' (HTTPS Only) flag on the trusted_computer cookie?
        cookie_same_site: "strict"     # The same-site option of the cookie, can be "lax" or "strict"
        extend_lifetime: true          # Automatically extend lifetime of the trusted cookie on re-login

    # Google Authenticator config
    google:
        enabled: true                  # If Google Authenticator should be enabled, default false
        server_name: '%domain%'        # Server name used in QR code
        issuer: '%company_name%'               # Issuer name used in QR code
        template: CrmBundle/Security/2fa.html.twig

    # The security token classes, which trigger two-factor authentication.
    # By default the bundle only reacts to Symfony's username+password authentication. If you want to enable
    # two-factor authentication for other authentication methods, add their security token classes.
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Core\Authentication\Token\RememberMeToken

    # A list of IP addresses, which will not trigger two-factor authentication
#    ip_whitelist:
#        - 127.0.0.1
```
