### ISSUE TITLE
require second factor only for some routes or a specified firewall

### ISSUE THREAD

**Issue by ghost** [scheb/two-factor-bundle#13]
I have actions in my app that have higher security requirements than others. So I'd like to require the second factor only for these routes. I imagine two alternative strategies:
- define two different firewalls and only require the second factor for one of this firewalls
- somehow mark (annotate) or list (config) the routes that require the second factor

I'd like to contribute this feature to your bundle, if we can find an implementation that is generic and backwards compatible.

**Comment by scheb** [comment]
I think the firewall solution wouldn't work, because from what I know authentication is separated between firewalls. Which means when you're authenticated in firewall A, you're not authenticated in firewall B. So you would have to log in again when you switch to a different area.

What could work is if I add something similar to the "exclude_pattern" configuration option, but the other way round, like an "include_pattern" which is a list of URLs that should be protected with two-factor authentication and the rest isn't.

**Comment by thkoch2001** [comment]
I found the 'context' firewall configuration key: http://symfony.com/doc/current/reference/configuration/security.html#firewall-context

So one can share the authentication state between multiple firewalls. Now the two-factor-bundle only needs to be configurable on a per-firewall base. It would actually make more sense to have the whole bundle configurable per firewall, e.g.:

```
scheb_two_factor:
  firewalls:
    somename: main # mapping from firewall names to configurations from below  
  configurations:
    name: main
    trusted_computer:
        enabled: false
        cookie_name: trusted_computer
        cookie_lifetime: 5184000 
    exclude_pattern: ~
```
