### ISSUE TITLE
Clarification needed on setup steps

### ISSUE THREAD

**Issue by bmendonca** [scheb/two-factor-bundle#152]
Hello there! I've been following along on the steps for setting up the email authentication and seem to have hit a stoppage point that I was hoping to get more specifics about the setup. I've got the bundle added to composer, AppKernel.php, config.yml, security.yml, my User Entity, and my token setup configured based on the token I found in the debugger profile when I was successfully logged in. Now I am at the point where I am attempting to login and while I do get the `TwoFactorToken`, I am not able to proceed any further. I'm not seeing a pop-up window or the form located at `vendor\scheb\two-factor-bundle\Resources\views\Authentication\form.html.twig`. 

My question is whether there are some Twig components that I should be adding into my login form Twig file or if there are additional steps I need to take to get this set up properly? 

Using:
schebe/two-factor-bundle version 2.7.1
PHP 7.1.3
Symfony 3.4.13

Thanks so much!

**Comment by bmendonca** [comment]
Hello there and thank you for your help! I see my own authentication form, but after attempting to login, it refers me back to the login form. In more detail:

I'm at http://127.0.0.1:8000/login and I enter my email address username and my password into the login form and click sign in. My token class changes from `AnonymousToken` to `TwoFactorToken` and I end up back to the login page http://127.0.0.1:8000/login without proceeding to http://127.0.0.1:8000/ (the main page of my test app). The login form is the exact same as when I had loaded it anonymously except for that I have the new token.

Here's my security.yml for the test project I'm working on:

```
security:
    encoders:
        AppBundle\Entity\User: bcrypt
    providers:
        database_users:
            entity: { class: AppBundle:User, property: email }
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
          anonymous: ~
          guard:
              authenticators:
                  - app.form_login_authenticator
          logout:
              path: /logout
              target: /login
          two_factor:
            auth_form_path: /2fa          # The route name you have used in the routes.yaml
            check_path: /2fa_login_check  # The route name you have used in the routes.yaml
            default_target_path: /

    role_hierarchy:
        ROLE_ADMIN: [ROLE_SYS_FULL]
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        ROLE_SYS_MAILING: ROLE_SYS
        ROLE_SYS_PP: ROLE_SYS
        ROLE_SYS_FULL: [ROLE_SYS_MAILING,ROLE_SYS_PP]
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/activate, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/, role: ROLE_USER }
        - { path: ^/2fa, role: IS_AUTHENTICATED_2FA_IN_PROGRESS }
```

Thanks so much for any advice you can provide.
