### ISSUE TITLE
fosuserbundle integration

### ISSUE THREAD

**Issue by gulaandrij** [scheb/two-factor-bundle#153]
Hello, im trying to integrate fosuserbundle and 2fa, but im getting this error 
```
Not configuring explicitly the provider for the "two_factor" listener on "main" firewall is ambiguous as there is more than one registered provider.

```
this is my config:
```
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: argon2i

    role_hierarchy:
        ROLE_ADMIN_CONTENT:     ROLE_USER
        ROLE_ADMIN:             ROLE_ADMIN_CONTENT
        ROLE_SUPER_ADMIN:       ROLE_ADMIN

    providers:
        in_memory: { memory: ~ }
        fos_userbundle:
            id: fos_user.user_provider.username_email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            two_factor:
                auth_form_path: /2fa          # The route name you have used in the routes.yaml
                check_path: /2fa_login_check  # The route name you have used in the routes.yaml
                default_target_path: /
            logout:       true
            anonymous:    true
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN_CONTENT }
        - { path: ^/doc, role: ROLE_ADMIN }

```

can someone say what is wrong here

**Comment by scheb** [comment]
It wants you to add `provider: fos_userbundle` under the `two_factor` node since you have two user providers registered. Weird thing is the `two_factor` bundle doesn't even have such a configuration option. Looks like some higher-level component of the security bundle is making assumptions about how the configuration of individual authentication providers should look like.

You can try adding it, but I doubt it'd be accepted. Alternative would be, that you're removing that `in_memory` provider, if you don't need it.

**Comment by gulaandrij** [comment]
tnx, it helped

**Comment by jtokoev** [comment]
> tnx, it helped
How did you do that ? Can you show the security? I have the same problem

**Comment by scheb** [comment]
@jtokoev It happens when you have multiple user providers configured and Symfony Security Bundle is forcing every authentication provider in your firewall to have a user provider configured. 

To work around this issue, configure a `provider` on the `two_factor` level:

```yaml
# config/packages/security.yaml
security:
    firewalls:
        yourFirewallName:
            # ...
            two_factor:
                # If you have multiple user providers registered, Symfony's security extension requires you to configure
                # a user provider. You're forced to configure this node, although it doesn't have any effect on the
                # TwoFactorBundle. So set this to any of your user providers, it doesn't matter which one.
                provider: any_user_provider
```

https://github.com/scheb/two-factor-bundle/blob/master/Resources/doc/configuration.md
