### ISSUE TITLE
Possible to add a way to load whitelist IPs from a service

### ISSUE THREAD

**Issue by markbeazley** [scheb/two-factor-bundle#162]
It would be helpful to have the bundle be able to use a service or event to load the whitelist IP addresses from the application in someway. My application already contains a list of IP addresses that I want to whitelist and it would be nice to not have to duplicate them to the config file. 

If possible it would also allow for different users to have a different IP address whitelist or allow the application to change the whitelist based on other rules.

**Comment by scheb** [comment]
Sounds doable. Would need to add a service+interface responsible for providing the whitelisted ips and then make that service configurable just like the other customizable services in the bundle. Any thoughts?

**Comment by scheb** [comment]
Meh, that sounds like a hack to me. Mutating an object on an event and then expecting that it is used in that state on the other side isn't really a good practice. I could do the service+interface solution in a backwards-compatible way, that wouldn't require and config changes for existing users, but would enable the use of a different whitelist provider, if needed. Will give it a try then...

**Comment by scheb** [comment]
Just released v.3.13.0

See: https://github.com/scheb/two-factor-bundle/blob/master/Resources/doc/configuration.md

```yaml
# config/packages/scheb_two_factor.yaml
scheb_two_factor:
    # If you want to have your own implementation to retrieve the whitelisted IPs.
    # The configuration option "ip_whitelist" becomes meaningless in such a case.
    ip_whitelist_provider: acme.custom_ip_whitelist_provider
```
