### ISSUE TITLE
Logout request intercepted by TwoFactorListener

### ISSUE THREAD

**Issue by aguidis** [scheb/two-factor-bundle#168]
Hello,

I have some trouble to logout during the 2fa process. I used xdebug to trace the request and it appears that the`TwoFactorListener` is triggered before the default `Symfony\Component\Security\Http\Firewall\LogoutListener`.

When I click on the logout link (in the default form template), I'm redirected to same page `/2fa` because of this [condition](https://github.com/scheb/two-factor-bundle/blob/master/Security/Http/Firewall/TwoFactorListener.php#L173).

There is no condition to catch this scenario (logout request).

I just tried to fix it with theses lines to see if I manage to logout and it works:

```
if  ($request->attributes->get('_route') === 'my_logout_route') {
     return;
}
```

Do you think this issue is related to my configuration ?

- **security.yaml**

```
security:
    firewalls:
        backoffice:
            pattern: ^/backoffice
            provider: user_provider
            guard:
                authenticators:
                    - AppBundle\Security\Guard\BackofficeLoginAuthenticator
            two_factor:
                auth_form_path: back_office_2fa_login
                check_path: back_office_2fa_login_check
                default_target_path: /backoffice
            anonymous: true
            logout:
                # the user will only be logged out from the current firewall and not the other ones.
                invalidate_session: false
                csrf_parameter: _bo_csrf_token
                csrf_token_id: bo_login_item
                path: /backoffice/deconnexion
                target: /backoffice/connexion
```

- packages/scheb_two_factor.yaml

```
scheb_two_factor:
    google:
        enabled: true
        server_name: myapp.com
        issuer: MyApp
        digits: 6
        template: backoffice/pages/security/2fa_form.html.twig

    security_tokens:
        - Symfony\Component\Security\Guard\Token\PostAuthenticationGuardToken

```

Cheers
