### ISSUE TITLE
Unrecognized option "provider" under "security.firewalls.main.two_factor"

### ISSUE THREAD

**Issue by alex2005git** [scheb/two-factor-bundle#179]
security.yml
```
# ...
security:
    providers:
        form_login:
            id: App\Security\User\FormLoginUserProvider

        oauth:
            id: App\Security\User\OAuthUserProvider

    firewalls:
        main:
            form_login:
                provider: form_login

            oauth:
                provider: oauth

            two_factor:
                provider: form_login
# ...
```

I'm getting `Unrecognized option "provider" under "security.firewalls.main.two_factor"`, without `provider` i'm getting `Not configuring explicitly the provider for the "two_factor" listener on "main" firewall is ambiguous as there is more than one registered provider.` 

Latest symfony version.
