### ISSUE TITLE
AdvancedUserInterface is not supported

### ISSUE THREAD

**Issue by micronax** [scheb/two-factor-bundle#206]
I currently face some problems while implementing the 2FA in a project:

I followed all steps from the documentation and was successfully able to enable 2FA for a testuser with Google Authenticator.

After login I get redirected to /2fa (default configuration). When I successfully pass the 2FA-challenge (I get `User has been two-factor authenticated successfully` in the logs) I get redirected to the default route behind the firewall. Then I get redirected to the login form again because of insufficient role permissions. When I re-login or directly point to a route behind the firewall I get redirected again to /2fa.

In the symfony debug toolbar I see, I have a TwoFactorToken with a UsernamePasswordToken embedded which contains the correct roles. But the TwoFactorToken itself seems like containing no roles at all.

**The profile output of the /login route:**
![Bildschirmfoto 2019-04-22 um 10 12 49](https://user-images.githubusercontent.com/1337823/56490991-5b177e00-64e7-11e9-96ec-0464721c0976.png)

**Output of `dump($tokenStorage->getToken());` at the /login route:**
![Bildschirmfoto 2019-04-22 um 10 02 46](https://user-images.githubusercontent.com/1337823/56491001-623e8c00-64e7-11e9-8a97-a727bcf86887.png)

**Some more debugging output:**
![Bildschirmfoto 2019-04-22 um 10 00 19](https://user-images.githubusercontent.com/1337823/56491030-784c4c80-64e7-11e9-8b45-5f9acab4af19.png)

**My Configuration:**

**routes.yml**
```
2fa_login:
    path: /2fa
    defaults:
        _controller: "scheb_two_factor.form_controller:form"

2fa_login_check:
    path: /2fa_check
```

**config.yml**
```
scheb_two_factor:
    google:
        enabled:     true
```

**security.yml**
```
firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Main protected user-area
        webgui:
            pattern:   ^/
            anonymous: ~
            provider: entity_provider
            switch_user: { role: ROLE_ADMIN_SWITCH_USER, parameter: _app_switch_user }
            form_login:
                login_path: login
                check_path: login
                default_target_path: login_switch_redirect
                use_referer: true
            logout:
                path:   /logout
                target: /login
            two_factor:
                auth_form_path: 2fa_login
                check_path:     2fa_login_check
                default_target_path: /dashboard
                always_use_default_target_path: false
```
