### ISSUE TITLE
Redirect from TwoFactorAuthenticationSubscriber

### ISSUE THREAD

**Issue by alexsobolenko** [scheb/two-factor-bundle#207]
I want to implement brute-froce protection. Upon reaching a certain number of failure attempts of entering the code to block the user. How can I redirect from an interrupt handler? This code does not give the desired result:

```
public function onAuthenticationFailure(TwoFactorAuthenticationEvent $event): ?RedirectResponse
{
    /* some code */
    if (/* lock condition */) {
        return new RedirectResponse($this->router->generate('auth_fail'));
    }
    return null;
}
```

**Comment by scheb** [comment]
Event listeners are just callback methods, they don't have a return value. To force a redirect, you could replace the failure handler with a custom implementation.

See: https://github.com/scheb/two-factor-bundle/blob/master/Resources/doc/configuration.md
```yaml
security:
    firewalls:
        yourFirewallName:
            # ...
            two_factor:
                failure_handler: acme.custom_failure_handler # Use a custom failure handler instead of the default one
```

Default implementation is this: https://github.com/scheb/two-factor-bundle/blob/master/Security/Http/Authentication/DefaultAuthenticationFailureHandler.php
