### ISSUE TITLE
Cancel the 2FA process don't redirect to login page

### ISSUE THREAD

**Issue by tony-tran** [scheb/two-factor-bundle#209]
Hi,

I have the same problem as https://github.com/scheb/two-factor-bundle/issues/203 and https://github.com/scheb/two-factor-bundle/issues/199.

When I click on "cancel", I go to `/logout` and directly redirect to `/2fa_login`.
Do you have any idea please ? 

Thank you in advance. 

```
#security.yaml
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt))/
            security: false
        admin:
            host: '%app_admin_host_regexp%'
            provider: users
            anonymous: ~
            user_checker: App\Security\UserChecker
            form_login:
                login_path: app_login
                check_path: app_login
                username_parameter: email
                password_parameter: password
                csrf_parameter: _user_csrf
                csrf_token_id: authenticate_user
                csrf_token_generator: security.csrf.token_manager
                default_target_path: sonata_admin_dashboard
                use_referer: true
            logout:
                path: app_logout
                target: app_login
            two_factor:
                auth_form_path: 2fa_login
                check_path: 2fa_login_check

        main:
            anonymous: ~

    access_control:
        - {
              path: '^/logout',
              role: IS_AUTHENTICATED_ANONYMOUSLY,
              host: '%app_admin_host_regexp%',
          }
        - {
              path: '^/double-authentification$',
              roles: IS_AUTHENTICATED_2FA_IN_PROGRESS,
              host: '%app_admin_host_regexp%',
          }
        - {
              path: '^/login',
              roles: IS_AUTHENTICATED_ANONYMOUSLY,
              host: '%app_admin_host_regexp%',
          }
```

```
#routes.yaml

app_logout:
    host: '%app_admin_host%'
    path: /logout
    methods: GET
```

**Comment by scheb** [comment]
access_control looks good. Please find out where the redirect is coming from, then we can see how to solve it.

**Comment by micronax** [comment]
I think there are problems with the `use_referer` option enabled on `form_login`. I also get some strange behavior when this is enabled.

I successfully login, but get redirected to /login page. When I enter /2fa or any other valid route behind the firewall I get redirected to /2fa and can login.

My configuration:

```
webgui:
            pattern:   ^/
            anonymous: ~
            provider: entity_provider
            form_login:
                login_path: login
                check_path: login
                default_target_path: /dashboard
#                use_referer: true # WHEN I enable this, i get redirected back to /login after successfuly login
            logout:
                path:   /logout
                target: /login
            two_factor:
                auth_form_path: 2fa_login
                check_path:     2fa_login_check
                default_target_path: /dashboard
```
