### ISSUE TITLE
Release 3.20.0 (and 4.3.0?) breaks Google template configuration

### ISSUE THREAD

**Issue by jonathanbull** [scheb/two-factor-bundle#227]
**Bundle version**: 3.20.0
**Symfony version**: 4.2.4

**Description**
An upgrade from 3.19.21 to 3.20.0 has stopped our template from loading. My best guess is that this is related to https://github.com/scheb/two-factor-bundle/pull/224 as the `scheb_two_factor.security.google.form_renderer` is now an alias to `scheb_two_factor.security.form_renderer`. This accepts `%scheb_two_factor.email.template%` as the argument, so `%scheb_two_factor.google.template%` is never passed along.

As a short term solution we've changed our config from this:

```
scheb_two_factor:
    google:
        enabled: true
        issuer: Foo
        template: account/google_2fa.html.twig
```

to this:

```
scheb_two_factor:
    email:
        template: account/google_2fa.html.twig
    google:
        enabled: true
        issuer: Foo
        template: account/google_2fa.html.twig
```

**To Reproduce**
- Upgrade to 3.20.0 and set a `schedb_two_factor.google.template` config variable (do not define `schedb_two_factor.email.template`)
- Sign in - the Google template choice will be ignored
