### ISSUE TITLE
Why my trusted devices are not saved to cookies?

### ISSUE THREAD

**Issue by alexsobolenko** [scheb/two-factor-bundle#232]
**Bundle version**: 3.22.0
**Symfony version**: 4.2.8

I confirured `config/packages/scheb_two_factor.yaml`:
```yaml
scheb_two_factor:
...
    trusted_device:
        enabled: true
        lifetime: 100  # for test
        extend_lifetime: true
...
```
but I see that `$this->hasTrustedDeviceParameter($request)` in `scheb\two-factor-bundle\Security\Http\Firewall\TwoFactorListener.php` always returns `false`

The situation has not changed after upgrading to v4.5.0.
