### ISSUE TITLE
Never ending redirect after update to 4.7.0

### ISSUE THREAD

**Issue by bytehead** [scheb/two-factor-bundle#235]
**Bundle version**: 4.7.0
**Symfony version**: 4.3.4

**Description**
After updating from `4.6.0` to `4.7.0` I get never ending redirects after submitting the verify code. Any idea what it could be?

**Comment by scheb** [comment]
Could you please track down in which code path the redirect is triggered? Maybe [intercept_redirects](https://symfony.com/doc/master/reference/configuration/web_profiler.html#intercept-redirects) can help.

**Comment by bytehead** [comment]
Yes, surely :).

I get redirected here: https://github.com/scheb/two-factor-bundle/blob/15bad1e41b2f660760221f5022b632c212245f07/Security/Http/Firewall/TwoFactorListener.php#L206

**Comment by bytehead** [comment]
What's the matter with the new `TwoFactorProviderPreparationRecorder`?

**Comment by scheb** [comment]
Hmm, that doesn't really help me because that line doesn't produce the redirect. Is there an exception thrown and therefore you're ending up in https://github.com/scheb/two-factor-bundle/blob/15bad1e41b2f660760221f5022b632c212245f07/Security/Http/Firewall/TwoFactorListener.php#L209-L211 ? If so, can you tell what the exception is?

> What's the matter with the new TwoFactorProviderPreparationRecorder?
That is there to remember in the session if the TwoFactorProvider (email, google, etc.) has been prepared. Is that one causing the issue?

**Comment by bytehead** [comment]
Yes, I get this exception: `The two-factor provider %provider% has not been prepared.` here: https://github.com/scheb/two-factor-bundle/blob/15bad1e41b2f660760221f5022b632c212245f07/Security/Authentication/Provider/TwoFactorAuthenticationProvider.php#L84

**Comment by bytehead** [comment]
To clear up, I'm using a custom provider.

**Comment by scheb** [comment]
Could it be that you're using a custom implementation of `TwoFactorTokenInterface`?

**Comment by bytehead** [comment]
Nope, just the regular `TwoFactorToken`:
```
TwoFactorToken^ {#514 ▼
  -authenticatedToken: UsernamePasswordToken^ {#407 ▶}
  -credentials: ""
  -providerKey: "frontend"
  -attributes: []
  -twoFactorProviders: array:1 [▶]
}
```

**Comment by scheb** [comment]
Then we have to go step-by-step to find out why the preparation step is never triggered. The idea is, when the two-factor for is shown to the user, the preparation for the current two-factor provider is triggered. Makes things a bit easier since you have only one.

1) When the two-factor form is shown an event `scheb_two_factor.authentication.form` should be dispatched in https://github.com/scheb/two-factor-bundle/blob/15bad1e41b2f660760221f5022b632c212245f07/Security/Http/Firewall/TwoFactorListener.php#L166 Please check that the event is in fact dispatched. The token should be a `TwoFactorToken`

2) The `scheb_two_factor.authentication.form` event should be handled in: https://github.com/scheb/two-factor-bundle/blob/15bad1e41b2f660760221f5022b632c212245f07/Security/TwoFactor/Provider/TwoFactorProviderPreparationListener.php#L86-L93 The `if` statement should be `true`, otherwise you should check why it evalutes to `false`. Either there is no `TwoFactorToken` present or the firewall name doesn't match the token's `providerKey`.

3) At the end of the request, the method https://github.com/scheb/two-factor-bundle/blob/15bad1e41b2f660760221f5022b632c212245f07/Security/TwoFactor/Provider/TwoFactorProviderPreparationListener.php#L95-L121 should be called, execute the preparation and remember it in the session (line 116).

4) In the following request, when the two-factor authentication code is sent, it should remember session that the provider has been prepared. If everything else worked, this could mean session data was not persisted.

**Comment by bytehead** [comment]
Thanks for your help - very appreciated! 👍

1. Will not be executed. In my setup the `verify` input can be everywhere (not a fixed path) and https://github.com/scheb/two-factor-bundle/blob/15bad1e41b2f660760221f5022b632c212245f07/Security/Http/Firewall/TwoFactorListener.php#L188 won't return `true` in this cases. 
And if there is the `POST` request with the `verify` value, it gets interrupted by `$this->isCheckAuthCodeRequest($request)` on line 158: https://github.com/scheb/two-factor-bundle/blob/15bad1e41b2f660760221f5022b632c212245f07/Security/Http/Firewall/TwoFactorListener.php#L158

**Comment by bytehead** [comment]
I can fix it by dispatch the `scheb_two_factor.authentication.form` event manually, if the form gets displayed.

**Comment by scheb** [comment]
This is what you need:

```yaml
# config/packages/security.yaml
security:
    firewalls:
        yourFirewallName:
            # ...
            two_factor:
                # Some two-factor providers need to be "prepared", usually a code is generated and sent to the user. Per
                # default, this happens when the two-factor form is shown. But you may want to execute preparation
                # earlier in the user's journey.
                prepare_on_login: false          # If the two-factor provider should be prepared right after login
                prepare_on_access_denied: false  # The the two-factor provider should be prepared when the user has to
                                                 # to complete two-factor authentication to view a page. This would
                                                 # prepare right before redirecting to the two-factor form.
```

https://github.com/scheb/two-factor-bundle/blob/master/Resources/doc/configuration.md
