### ISSUE TITLE
Invalid Barcode exception in Google Authenticator due to the issuer name

### ISSUE THREAD

**Issue by spointecker** [scheb/two-factor-bundle#243]
**Bundle version**: 4.7.1
**Symfony version**: 4.3.5

**Description**
We are successfully using the bundle to use 2FA. We just have the problem that we can´t use the issuer option for google authentication. If we do not use this option we can add the QR code to the authenticator app without any problem but if I set the option `issuer` the scanning fails with an exception: "Invalid barcode".
Without a name for the authentication code in the app it is hard to find the correct 2FA code.

Anyone experiencing something similar?

**Comment by scheb** [comment]
Do you have any non-letter characters in your issuer name? If so, could you try using a simple letter-only string? I want to make sure it's not an encoding problem.

**Comment by spointecker** [comment]
Unfortunately not, config is quite simple:
```
scheb_two_factor:
  google:
    enabled: true
    issuer: "company admin"
    template: 'APP..:2fa_form.html.twig'
```
