### ISSUE TITLE
Google Authenticator does not load in DI container on Symfony 4.3.8

### ISSUE THREAD

**Issue by pavlakis** [scheb/two-factor-bundle#246]
**Bundle version**: 4.8.0
**Symfony version**: 4.3.8

**Description**

In Symfony 4, the Google Authenticator `scheb_two_factor.security.google_authenticator` is not loaded in the DI container.

**To Reproduce**

1. Install bundle 4
2. Use the flex recipe
3. Run `bin/console debug:container` to see if it is loaded
4. Create the action as shown in [Documentation](https://github.com/scheb/two-factor-bundle/blob/master/Resources/doc/providers/google.md#generating-a-secret-code) and see the autowire error

**Comment by scheb** [comment]
Do you have the "Google Authenticator" authentication activated in the bundle configuration?

https://github.com/scheb/two-factor-bundle/blob/master/Resources/doc/configuration.md

```
# config/packages/scheb_two_factor.yaml
scheb_two_factor:
    google:
        enabled: true                  # If Google Authenticator should be enabled, default false
```

**Comment by pavlakis** [comment]
Yes. As per the docs.
This is my setup:
```
scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
    google:
        enabled: true
```

**Comment by scheb** [comment]
Do you see any other "scheb_two_factor.*" services in the DI?

And please try to clear the cache.

**Comment by pavlakis** [comment]
Probably it was just cache as it is picking it up now. Thanks.

Should probably turn this into a support ticket.

For some reason `2FA` does not kick in after a successful authentication.
Any guidance on that?

```
        main:
            context: web
            anonymous: ~
            two_factor:
                auth_form_path: 2fa_login
                check_path: 2fa_login_check
```
