### ISSUE TITLE
Type error: Too few arguments to function Scheb\TwoFactorBundle\Controller\FormController::__construct(), 0 passed

### ISSUE THREAD

**Issue by herrieb** [scheb/two-factor-bundle#286]
**Bundle version**: v4.15.0
**Symfony version**: 3.4
**PHP version**: 7.1.22

**Description**
I am following the installation guide as provided by the installation.md
where i am trying to set the controller location in the config/routes.yaml

```yaml 
# config/routes.yaml
2fa_login:
    path: /2fa
    defaults:
        _controller: "scheb_two_factor.form_controller:form"
```

this doesnt work as form_controller does not exist at this location. 

but: 
```yaml
2fa_login:
  path: /2fa
  defaults:
    _controller: "SchebTwoFactorBundle:form:form"
```

does exist. but it does not work as it needs 5 variables in the _construct which i do not have.
I'm kind of stuck here. If it helps, the symfony version has been updated from 2.7 to 3.4

The specific error message i am getting right now is;
HTTP 500 Internal Server Error
Type error: Too few arguments to function Scheb\TwoFactorBundle\Controller\FormController::__construct(), 0 passed in C:\Users\user\Projects\test\app\cache\dev\jms_diextra\controller_injectors\SchebTwoFactorBundleControllerFormController.php on line 13 and exactly 5 expected
