### ISSUE TITLE
How to use the two factor auth in combination with manual authentication

### ISSUE THREAD

**Issue by alyamovsky** [scheb/two-factor-bundle#297]
**Bundle version**: 4.18.2
**Symfony version**: 4.4.11

**Description**
Hi! Is it possible somehow to trigger the two factor auth for a user when he is authenticated manually with for example `$guardAuthenticatorHandler->authenticateUserAndHandleSuccess`?

I tried to combine this with 2fa, but it's always bypassed while the same user is properly redirected to the 2fa form if authenticated through the login form.

**Additional Context**
the successful authentication:
```php
$guardAuthenticatorHandler->authenticateUserAndHandleSuccess($user, $request, $myDefaultAuthenticator, 'main')`?
```

scheb_two_factor.yaml:
```yaml
scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Guard\Token\PostAuthenticationGuardToken
```
my security profiler:
![image](https://user-images.githubusercontent.com/23259219/91557305-ea833b80-e93c-11ea-978e-fef500365f95.png)
