### ISSUE TITLE
2FA by api + jwt

### ISSUE THREAD

**Issue by tumbochka** [scheb/two-factor-bundle#299]
**Bundle version**: 5.1.0
**Symfony version**: 5.1.5

**Description**

I want to integrate 2fa with api jwt login. The possible flow is:

1. A client sends a username and a password to the login endpoint
2. The login endpoint returns him 401 with WWW-Authenticate header with the required  authType (depending on 2fa method)
3. The client checks the authType and performs a request to the challenge/get endpoint with the username/password. The endpoint checks the username and password and returns a challengeId. Also 2fa is performed, for example the user receives an email.
4. The client sends request to the  challenge/verify endpoint with the username, the password, the challengeId, returned by the challenge/get endpoint and the 2fa code user got and entered, The challenge/verify endpoint verifies the provided information and returns a 2fa token
5. The client  performs a request to the login controller again with the username, password and Authorization header with authType and 2fa token.
6. The client is authenticated (gets a jwt access token).

Does the flow look good? Challenge token can be used to store a state between the requests. What is the best way to implement this? A custom security provider as was described here? https://github.com/scheb/two-factor-bundle/issues/283

Thank you :)

**Comment by scheb** [comment]
Did you check this? https://github.com/scheb/two-factor-bundle/blob/4.x/Resources/doc/api.md

**Comment by tumbochka** [comment]
@scheb oh, thank you.

**Comment by tumbochka** [comment]
@scheb  Hello, I checked the flow and implemented the handlers. For now my AuthenticationSuccessHandler works but the token it gets on json login is UsernamePasswordToken.
What else should I do? How can I init 2fa via api and sent a 2fa code to get a full authentication?

My config:


```
# See the configuration reference at https://github.com/scheb/2fa/blob/master/doc/configuration.md
scheb_two_factor:
  google:
    enabled: true
#  email:
#    enabled: true
  security_tokens:
    - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
    - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
```

My firewalls:

```
   firewalls:
        refresh:
            pattern: ^/api/token/refresh
            security: false

        login:
            pattern:  ^/api/login
            lazy: true
            json_login:
                check_path:               /api/login
                success_handler:          App\Security\AuthenticationSuccessHandler
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
            two_factor:
                authentication_required_handler:         App\Security\TwoFactorAuthenticationRequiredHandler
                success_handler:          App\Security\TwoFactorAuthenticationSuccessHandler
                failure_handler:          App\Security\TwoFactorAuthenticationFailureHandler

        api:
            json_login:
                check_path:               /api/login
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
            two_factor:
                authentication_required_handler:         App\Security\TwoFactorAuthenticationRequiredHandler
                success_handler:          App\Security\TwoFactorAuthenticationSuccessHandler
                failure_handler:          App\Security\TwoFactorAuthenticationFailureHandler
```
