### ISSUE TITLE
 impossible to go through page 2fa during login

### ISSUE THREAD

**Issue by TheoDeberles** [scheb/two-factor-bundle#302]
Hello 

**Bundle version**: 4.18
**Symfony version**: 4.4.7

**Description**
Hello, I would like to integrate a 2fa in my project. After following the doc and adding this conf in my project, I don't go to page 2fa after logging in my user.
Currently I do not see what is preventing the passage.
Sometime I also had a symfony mistake : 'Google is not prepared

I give you the conf of my security.yml file

```
security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        user_provider:
            entity:
                class: AppBundle\Entity\UserClient
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            context: corum
            pattern: ^/admin
            provider: fos_userbundle
            form_login:
                check_path: fos_user_security_check
                login_path: /admin/login
                default_target_path: easyadmin
            logout:
                path: /admin/logout
                target: /admin
            anonymous: true
            logout_on_user_change: true
            switch_user: true

        main:
            context: corum
            provider: user_provider
            pattern: ^/
            user_checker: AppBundle\Security\UserChecker

            form_login:
                provider: user_provider
                login_path: /login
                check_path: /login
                csrf_token_generator: security.csrf.token_manager
                default_target_path: app_dashboard
                
            two_factor:
                provider: user_provider
                auth_form_path: /2fa
                check_path: /2fa_check
                default_target_path: app_dashboard
                multi_factor: false

            logout:
                path: /logout
                target: /
                
            anonymous: true
            logout_on_user_change: true
            switch_user: true



    encoders:
        bcrypt:
            algorithm: bcrypt
        argon2i:
            algorithm: argon2i

    role_hierarchy:
        ROLE_ASSET_MANAGER: [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]
        ROLE_ADMIN: ROLE_ASSET_MANAGER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    access_control:
       [.....]
      - { path: ^/, roles: [ROLE_TENANT, ROLE_PROVIDER] }
      - { path: ^/2fa, role: IS_AUTHENTICATED_2FA_IN_PROGRESS }

```
