### ISSUE TITLE
Login via email failed

### ISSUE THREAD

**Issue by excelwebzone** [scheb/two-factor-bundle#305]
**Bundle version**: 4.18.4
**Symfony version**: 4.3.11
**PHP version**: 7.2.10

**Description**

In my application I allow users to choose ether Google or Email providers. When using Google it works nicely (Login -> 2FA -> Admin). The issue is when using Email. Once I login it redirect to 2FA form; reviewing the profiler I can see the `TwoFactorToken` generated:

```
TwoFactorToken^ {#1005 ▼
  -authenticatedToken: UsernamePasswordToken {#623 …}
  -credentials: null
  -providerKey: "main"
  -attributes: [▼
    "remember_me_cookie" => [▼
      Cookie^ {#621 ▶}
    
  ]
  -twoFactorProviders: [▼
    "email"
  ]
}
```

And an email is being sent to me. When trying to confirm the code it redirect me back to the login. Looking at the log file I can see the error `Cannot refresh token because user has changed`. I believe this could be as a result of updating the `authCode` (field) as it regenerated and stored when form is created. Any thoughts how to fix it?

```yaml
scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken

    google:
        enabled: true

    email:
        enabled: true
        digits: 6
        sender_email: '%env(APP_EMAIL)%'
```
