### ISSUE TITLE
Not prompted for Google Authenticator code on login

### ISSUE THREAD

**Issue by patrickdamery** [scheb/two-factor-bundle#306]
**Bundle version**: 4.18.4
**Symfony version**: 3.4.35
**PHP version**: 7.2.24

**Description**
I'm trying to setup 2 factor authentication with Google Authenticator on a web app I'm working on. 

I've setup the User entity with the TwoFactorInterface and I have successfully generated the QR code and saved the secret to the database. However when I try logging in, I'm never prompted for the Google Authenticator Code. I've gone through the troubleshooting steps and I'm having trouble in step 4: getActiveTwoFactorProviders() is never called.

I've checked my bundle's configuration and I don't have anything whitelisted and have disabled trusted devices:
```yaml
scheb_two_factor:
    trusted_device:
        enabled: false

    google:
        enabled: true
        server_name: www.example.com      # Server name used in QR code
        issuer: Example           # Issuer name used in QR code
        digits: 6                      # Number of digits in authentication code
        window: 1
        template: security/2fa_form.html.twig

    ip_whitelist: ~

    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        #- Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
```

**Additional Context**
I've also had a look at my Login authenticator and can't see anything that would suggest that the roles are loaded by replacing the security token after login, although I haven't actually found where the Role is loaded. As far as I can tell it's a pretty standard implementation of AbstractFormLoginAuthenticator (I didn't write this project just adding 2fa to it).

```php
<?php

class LoginFormAuthenticator extends AbstractFormLoginAuthenticator
{

    use TargetPathTrait;

    private $em;
    private $router;
    private $passwordEncoder;
    private $csrfTokenManager;

    public function __construct(
        EntityManagerInterface $em,
        RouterInterface $router,
        UserPasswordEncoderInterface $passwordEncoder,
        CsrfTokenManagerInterface $csrfTokenManager
    ) {
        $this->em = $em;
        $this->router = $router;
        $this->passwordEncoder = $passwordEncoder;
        $this->csrfTokenManager = $csrfTokenManager;
    }

    public function getCredentials(Request $request)
    {
        $username = $request->request->get('_username');
        $password = $request->request->get('_password');
        $csrfToken = $request->request->get('_csrf_token');
        if (false === $this->csrfTokenManager->isTokenValid(new CsrfToken('authenticate', $csrfToken))) {
            throw new InvalidCsrfTokenException('Invalid CSRF token.');
        }

        if ($request->getSession()) {
            $request->getSession()->set(Security::LAST_USERNAME, $username);
        }

        return [
            'username' => $username,
            'password' => $password,
        ];
    }

    public function getUser($credentials, UserProviderInterface $userProvider)
    {
        $username = $credentials['username'];
        return $this->em->getRepository('AppBundle:User')
            ->findOneBy(['username' => $username]);
    }

    public function checkCredentials($credentials, UserInterface $user)
    {
        /** @var User $user */
        $password = $credentials['password'];
        if ($this->passwordEncoder->isPasswordValid($user, $password) && !$user->getDeletedAt()) {
            return true;
        }
        return false;
    }

    public function onAuthenticationSuccess(Request $request, TokenInterface $token, $providerKey)
    {
        $targetPath = null;
        // if the user hit a secure page and start() was called, this was
        // the URL they were on, and probably where you want to redirect to
        $targetPath = $this->getTargetPath($request->getSession(), $providerKey);

        if (!$targetPath) {
            $targetPath = $this->router->generate('dashboard');
        }

        return new RedirectResponse($targetPath);
    }

    protected function getLoginUrl()
    {
        return $this->router->generate('fos_user_security_login');
    }

    public function supports(Request $request)
    {
        if ($request->getPathInfo() != '/login_check' || $request->getMethod() != 'POST') {
            return false;
        }

        return true;
    }
}

```

**Comment by scheb** [comment]
Since you obviously reached step "3) On login, do you reach the end (return statement) of method Scheb\TwoFactorBundle\Security\Authentication\Provider\AuthenticationProviderDecorator::authenticate()" from the troubleshooting guide: What is the class of `$token` that you see here in line 94:

https://github.com/scheb/two-factor-bundle/blob/d85ddf71ab35acdd23a3b39efc82ce4a905756b5/Security/Authentication/Provider/AuthenticationProviderDecorator.php#L94-L96

That class must be listed in `security_tokens` in the configuration.

**Comment by patrickdamery** [comment]
Hey Scheb, thanks for your reply! I've added my token to `security_tokens` and now I'm getting as far as step 5. The method is returning an array containing the string 'google'. The user does have a googleAuthenticatorSecret defined and the method isGoogleAuthenticatorSecretEnabled() in the User model does return true. 

However I'm still not being prompted for the Google Authenticator code. Do you have any idea as to what could be the problem now?

**Comment by scheb** [comment]
What's the security token that you see in your session after login? Is it a `TwoFactorToken` or something else? You should see that in the debug toolbar.

And could you please post your `security.yaml`, thanks.

**Comment by patrickdamery** [comment]
It is a TwoFactorToken.

```
security:

    encoders:
        AppBundle\Entity\User: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        api_key_user_provider:
            id: AppBundle\Security\ApiKeyUserProvider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^(?!/api|/login$|/2fa|/2fa_check|/resetting)\S+
            logout_on_user_change: true
            stateless: false
            anonymous: ~
            form_login:
                default_target_path: dashboard

            logout: ~

            remember_me:
                secret: '%secret%'

            guard:
                authenticators:
                    - app.security.login_form_authenticator
            
            two_factor:
                csrf_token_generator: security.csrf.token_manager
                auth_form_path: 2fa_login    # The route name you have used in the routes.yaml
                check_path: 2fa_login_check  # The route name you have used in the routes.yaml

    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/2fa, role: IS_AUTHENTICATED_2FA_IN_PROGRESS }

```
