### ISSUE TITLE
Voter causes an infinite redirect for non-UsernamePasswordToken tokens

### ISSUE THREAD

**Issue by zerkms** [scheb/two-factor-bundle#62]
If you configure a project with `RememberMeToken` then when user is re-authenticated using the `RememberMe` cookie - voter's `return VoterInterface::ACCESS_DENIED;` turn the authentication process into an infinite loop.

It happens because:
1. `RememberMe` listener authenticates a user
2. On voter returns `ACCESS_DENIED`
3. Symfony's `Symfony\Component\Security\Http\Firewall\ExceptionListener` exception handler checks the user is not fully authenticated and performs a redirect (through `Symfony\Component\Security\Http\EntryPoint\FormAuthenticationEntryPoint::start()`
4. Go to step 2

Temporary solution: disable Voter

Permanent solution: the Voter implementation (and presence at all) should be reconsidered.

**Comment by umpirsky** [comment]
@zerkms I cannot reproduce it, my configuration:

```
scheb_two_factor:
    google:
        enabled: true
    trusted_computer:
        enabled: true
        cookie_secure: true
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Core\Authentication\Token\RememberMeToken

```

Do you have same config?
