### ISSUE TITLE
Google Authentication keep saying invalid code..

### ISSUE THREAD

**Issue by bogdandovgopol** [scheb/two-factor-bundle#99]
Hey,

Implemented Google Authentication as it is explained in documentation, generated Secret and QR. Scanned QR with app. Tried to login, but when I type code from APP, it's keep throwing that code is incorrect. 

I'm trying to implement it with FOSUserBundle. 
Looks like it's working when I'm trying to login at login page /login
But when I'm trying to login at /admin that's redirecting to /login, that doesn't work. 

config
```

scheb_two_factor:
    # Trusted computer feature
    trusted_computer:
        enabled: false                 # If the trusted computer feature should be enabled
        cookie_name: trusted_computer  # Name of the trusted computer cookie
        cookie_lifetime: 5184000       # Lifetime of the trusted computer cookie
        cookie_secure: false           # Set the 'Secure' (HTTPS Only) flag on the trusted_computer cookie
        cookie_same_site: "lax"     # The same-site option of the cookie, can be "lax" or "strict"

    # Regex pattern of paths you want to exclude from two-factor authentication.
    # Useful to exclude Assetic paths or other files from being blocked.
    # Example: ^/(css|js|images)/
    exclude_pattern: ~

    # POST/GET parameter names
    parameter_names:
        auth_code: _auth_code          # Name of the parameter containing the authentication code
        trusted: _trusted              # Name of the parameter containing the trusted flag
    google:
        enabled: true
        template: FOSUserBundle:Security:2nd-step.html.twig

    # The service which is used to persist data in the user object. By default Doctrine is used. If your entity is
    # managed by something else (e.g. an API), you have to implement a custom persister
    persister: scheb_two_factor.persister.doctrine

    # If your Doctrine user object is managed by a model manager, which is not the default one, you have to
    # set this option. Name of entity manager or null, which uses the default one.
    model_manager_name: ~

    # The security token classes, which trigger two-factor authentication.
    # By default the bundle only reacts to Symfony's username+password authentication. If you want to enable
    # two-factor authentication for other authentication methods, add their security token classes.
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
```

2nd-step.html.twig

```
<form class="form" action="" method="post">
    {% for flashMessage in app.session.flashbag.get("two_factor") %}
        <p class="error">{{ flashMessage|trans }}</p>
    {% endfor %}

    <p class="label"><label for="_auth_code">{{ "scheb_two_factor.auth_code"|trans }}</label></p>
    <p class="widget"><input id="_auth_code" type="text" autocomplete="off" name="_auth_code" /></p>
    {% if useTrustedOption %}<p class="widget"><label for="_trusted"><input id="_trusted" type="checkbox" name="_trusted" /> {{ "scheb_two_factor.trusted"|trans }}</label></p>{% endif %}
    <p class="submit"><input type="submit" value="{{ "scheb_two_factor.login"|trans }}" /></p>

    {# The logout link gives the user a way out if they can't complete the second step #}
    <p class="cancel"><a href="/logout">{{ "scheb_two_factor.cancel"|trans }}</a></p>
</form>
```
